package com.example.mandopokemon.Utiles;

import com.example.mandopokemon.R;

public class UtilImagenes {

    /**
     * Devuelve el id de la imagen del pokemon
     *
     * @param idPok Id del pokemon
     * @return id de la imagen que le corresponde
     */
    public static int getIdRecursoPokemon(int idPok) {
        switch (idPok) {
            case 1:
                return R.mipmap.pokemon1;
            case 2:
                return R.mipmap.pokemon2;
            case 3:
                return R.mipmap.pokemon3;
            case 4:
                return R.mipmap.pokemon4;
            case 5:
                return R.mipmap.pokemon5;
            case 6:
                return R.mipmap.pokemon6;
            case 7:
                return R.mipmap.pokemon7;
            case 8:
                return R.mipmap.pokemon8;
            case 9:
                return R.mipmap.pokemon9;
            case 10:
                return R.mipmap.pokemon10;
            case 11:
                return R.mipmap.pokemon11;
            case 12:
                return R.mipmap.pokemon12;
            case 13:
                return R.mipmap.pokemon13;
            case 14:
                return R.mipmap.pokemon14;
            case 15:
                return R.mipmap.pokemon15;
            case 16:
                return R.mipmap.pokemon16;
            case 17:
                return R.mipmap.pokemon17;
            case 18:
                return R.mipmap.pokemon18;
            case 19:
                return R.mipmap.pokemon19;
            case 20:
                return R.mipmap.pokemon20;
            case 21:
                return R.mipmap.pokemon21;
            case 22:
                return R.mipmap.pokemon22;
            case 23:
                return R.mipmap.pokemon23;
            case 24:
                return R.mipmap.pokemon24;
            case 25:
                return R.mipmap.pokemon25;
            case 26:
                return R.mipmap.pokemon26;
            case 27:
                return R.mipmap.pokemon27;
            case 28:
                return R.mipmap.pokemon28;
            case 29:
                return R.mipmap.pokemon29;
            case 30:
                return R.mipmap.pokemon30;
            case 31:
                return R.mipmap.pokemon31;
            case 32:
                return R.mipmap.pokemon32;
            case 33:
                return R.mipmap.pokemon33;
            case 34:
                return R.mipmap.pokemon34;
            case 35:
                return R.mipmap.pokemon35;
            case 36:
                return R.mipmap.pokemon36;
            case 37:
                return R.mipmap.pokemon37;
            case 38:
                return R.mipmap.pokemon38;
            case 39:
                return R.mipmap.pokemon39;
            case 40:
                return R.mipmap.pokemon40;
            case 41:
                return R.mipmap.pokemon41;
            case 42:
                return R.mipmap.pokemon42;
            case 43:
                return R.mipmap.pokemon43;
            case 44:
                return R.mipmap.pokemon44;
            case 45:
                return R.mipmap.pokemon45;
            case 46:
                return R.mipmap.pokemon46;
            case 47:
                return R.mipmap.pokemon47;
            case 48:
                return R.mipmap.pokemon48;
            case 49:
                return R.mipmap.pokemon49;
            case 50:
                return R.mipmap.pokemon50;
            case 51:
                return R.mipmap.pokemon51;
            case 52:
                return R.mipmap.pokemon52;
            case 53:
                return R.mipmap.pokemon53;
            case 54:
                return R.mipmap.pokemon54;
            case 55:
                return R.mipmap.pokemon55;
            case 56:
                return R.mipmap.pokemon56;
            case 57:
                return R.mipmap.pokemon57;
            case 58:
                return R.mipmap.pokemon58;
            case 59:
                return R.mipmap.pokemon59;
            case 60:
                return R.mipmap.pokemon60;
            case 61:
                return R.mipmap.pokemon61;
            case 62:
                return R.mipmap.pokemon62;
            case 63:
                return R.mipmap.pokemon63;
            case 64:
                return R.mipmap.pokemon64;
            case 65:
                return R.mipmap.pokemon65;
            case 66:
                return R.mipmap.pokemon66;
            case 67:
                return R.mipmap.pokemon67;
            case 68:
                return R.mipmap.pokemon68;
            case 69:
                return R.mipmap.pokemon69;
            case 70:
                return R.mipmap.pokemon70;
            case 71:
                return R.mipmap.pokemon71;
            case 72:
                return R.mipmap.pokemon72;
            case 73:
                return R.mipmap.pokemon73;
            case 74:
                return R.mipmap.pokemon74;
            case 75:
                return R.mipmap.pokemon75;
            case 76:
                return R.mipmap.pokemon76;
            case 77:
                return R.mipmap.pokemon77;
            case 78:
                return R.mipmap.pokemon78;
            case 79:
                return R.mipmap.pokemon79;
            case 80:
                return R.mipmap.pokemon80;
            case 81:
                return R.mipmap.pokemon81;
            case 82:
                return R.mipmap.pokemon82;
            case 83:
                return R.mipmap.pokemon83;
            case 84:
                return R.mipmap.pokemon84;
            case 85:
                return R.mipmap.pokemon85;
            case 86:
                return R.mipmap.pokemon86;
            case 87:
                return R.mipmap.pokemon87;
            case 88:
                return R.mipmap.pokemon88;
            case 89:
                return R.mipmap.pokemon89;
            case 90:
                return R.mipmap.pokemon90;
            case 91:
                return R.mipmap.pokemon91;
            case 92:
                return R.mipmap.pokemon92;
            case 93:
                return R.mipmap.pokemon93;
            case 94:
                return R.mipmap.pokemon94;
            case 95:
                return R.mipmap.pokemon95;
            case 96:
                return R.mipmap.pokemon96;
            case 97:
                return R.mipmap.pokemon97;
            case 98:
                return R.mipmap.pokemon98;
            case 99:
                return R.mipmap.pokemon99;
            case 100:
                return R.mipmap.pokemon100;
            case 101:
                return R.mipmap.pokemon101;
            case 102:
                return R.mipmap.pokemon102;
            case 103:
                return R.mipmap.pokemon103;
            case 104:
                return R.mipmap.pokemon104;
            case 105:
                return R.mipmap.pokemon105;
            case 106:
                return R.mipmap.pokemon106;
            case 107:
                return R.mipmap.pokemon107;
            case 108:
                return R.mipmap.pokemon108;
            case 109:
                return R.mipmap.pokemon109;
            case 110:
                return R.mipmap.pokemon110;
            case 111:
                return R.mipmap.pokemon111;
            case 112:
                return R.mipmap.pokemon112;
            case 113:
                return R.mipmap.pokemon113;
            case 114:
                return R.mipmap.pokemon114;
            case 115:
                return R.mipmap.pokemon115;
            case 116:
                return R.mipmap.pokemon116;
            case 117:
                return R.mipmap.pokemon117;
            case 118:
                return R.mipmap.pokemon118;
            case 119:
                return R.mipmap.pokemon119;
            case 120:
                return R.mipmap.pokemon120;
            case 121:
                return R.mipmap.pokemon121;
            case 122:
                return R.mipmap.pokemon122;
            case 123:
                return R.mipmap.pokemon123;
            case 124:
                return R.mipmap.pokemon124;
            case 125:
                return R.mipmap.pokemon125;
            case 126:
                return R.mipmap.pokemon126;
            case 127:
                return R.mipmap.pokemon127;
            case 128:
                return R.mipmap.pokemon128;
            case 129:
                return R.mipmap.pokemon129;
            case 130:
                return R.mipmap.pokemon130;
            case 131:
                return R.mipmap.pokemon131;
            case 132:
                return R.mipmap.pokemon132;
            case 133:
                return R.mipmap.pokemon133;
            case 134:
                return R.mipmap.pokemon134;
            case 135:
                return R.mipmap.pokemon135;
            case 136:
                return R.mipmap.pokemon136;
            case 137:
                return R.mipmap.pokemon137;
            case 138:
                return R.mipmap.pokemon138;
            case 139:
                return R.mipmap.pokemon139;
            case 140:
                return R.mipmap.pokemon140;
            case 141:
                return R.mipmap.pokemon141;
            case 142:
                return R.mipmap.pokemon142;
            case 143:
                return R.mipmap.pokemon143;
            case 144:
                return R.mipmap.pokemon144;
            case 145:
                return R.mipmap.pokemon145;
            case 146:
                return R.mipmap.pokemon146;
            case 147:
                return R.mipmap.pokemon147;
            case 148:
                return R.mipmap.pokemon148;
            case 149:
                return R.mipmap.pokemon149;
            case 150:
                return R.mipmap.pokemon150;
            case 151:
                return R.mipmap.pokemon151;
            case 152:
                return R.mipmap.pokemon152;
            case 153:
                return R.mipmap.pokemon153;
            case 154:
                return R.mipmap.pokemon154;
            case 155:
                return R.mipmap.pokemon155;
            case 156:
                return R.mipmap.pokemon156;
            case 157:
                return R.mipmap.pokemon157;
            case 158:
                return R.mipmap.pokemon158;
            case 159:
                return R.mipmap.pokemon159;
            case 160:
                return R.mipmap.pokemon160;
            case 161:
                return R.mipmap.pokemon161;
            case 162:
                return R.mipmap.pokemon162;
            case 163:
                return R.mipmap.pokemon163;
            case 164:
                return R.mipmap.pokemon164;
            case 165:
                return R.mipmap.pokemon165;
            case 166:
                return R.mipmap.pokemon166;
            case 167:
                return R.mipmap.pokemon167;
            case 168:
                return R.mipmap.pokemon168;
            case 169:
                return R.mipmap.pokemon169;
            case 170:
                return R.mipmap.pokemon170;
            case 171:
                return R.mipmap.pokemon171;
            case 172:
                return R.mipmap.pokemon172;
            case 173:
                return R.mipmap.pokemon173;
            case 174:
                return R.mipmap.pokemon174;
            case 175:
                return R.mipmap.pokemon175;
            case 176:
                return R.mipmap.pokemon176;
            case 177:
                return R.mipmap.pokemon177;
            case 178:
                return R.mipmap.pokemon178;
            case 179:
                return R.mipmap.pokemon179;
            case 180:
                return R.mipmap.pokemon180;
            case 181:
                return R.mipmap.pokemon181;
            case 182:
                return R.mipmap.pokemon182;
            case 183:
                return R.mipmap.pokemon183;
            case 184:
                return R.mipmap.pokemon184;
            case 185:
                return R.mipmap.pokemon185;
            case 186:
                return R.mipmap.pokemon186;
            case 187:
                return R.mipmap.pokemon187;
            case 188:
                return R.mipmap.pokemon188;
            case 189:
                return R.mipmap.pokemon189;
            case 190:
                return R.mipmap.pokemon190;
            case 191:
                return R.mipmap.pokemon191;
            case 192:
                return R.mipmap.pokemon192;
            case 193:
                return R.mipmap.pokemon193;
            case 194:
                return R.mipmap.pokemon194;
            case 195:
                return R.mipmap.pokemon195;
            case 196:
                return R.mipmap.pokemon196;
            case 197:
                return R.mipmap.pokemon197;
            case 198:
                return R.mipmap.pokemon198;
            case 199:
                return R.mipmap.pokemon199;
            case 200:
                return R.mipmap.pokemon200;
            case 201:
                return R.mipmap.pokemon201;
            case 202:
                return R.mipmap.pokemon202;
            case 203:
                return R.mipmap.pokemon203;
            case 204:
                return R.mipmap.pokemon204;
            case 205:
                return R.mipmap.pokemon205;
            case 206:
                return R.mipmap.pokemon206;
            case 207:
                return R.mipmap.pokemon207;
            case 208:
                return R.mipmap.pokemon208;
            case 209:
                return R.mipmap.pokemon209;
            case 210:
                return R.mipmap.pokemon210;
            case 211:
                return R.mipmap.pokemon211;
            case 212:
                return R.mipmap.pokemon212;
            case 213:
                return R.mipmap.pokemon213;
            case 214:
                return R.mipmap.pokemon214;
            case 215:
                return R.mipmap.pokemon215;
            case 216:
                return R.mipmap.pokemon216;
            case 217:
                return R.mipmap.pokemon217;
            case 218:
                return R.mipmap.pokemon218;
            case 219:
                return R.mipmap.pokemon219;
            case 220:
                return R.mipmap.pokemon220;
            case 221:
                return R.mipmap.pokemon221;
            case 222:
                return R.mipmap.pokemon222;
            case 223:
                return R.mipmap.pokemon223;
            case 224:
                return R.mipmap.pokemon224;
            case 225:
                return R.mipmap.pokemon225;
            case 226:
                return R.mipmap.pokemon226;
            case 227:
                return R.mipmap.pokemon227;
            case 228:
                return R.mipmap.pokemon228;
            case 229:
                return R.mipmap.pokemon229;
            case 230:
                return R.mipmap.pokemon230;
            case 231:
                return R.mipmap.pokemon231;
            case 232:
                return R.mipmap.pokemon232;
            case 233:
                return R.mipmap.pokemon233;
            case 234:
                return R.mipmap.pokemon234;
            case 235:
                return R.mipmap.pokemon235;
            case 236:
                return R.mipmap.pokemon236;
            case 237:
                return R.mipmap.pokemon237;
            case 238:
                return R.mipmap.pokemon238;
            case 239:
                return R.mipmap.pokemon239;
            case 240:
                return R.mipmap.pokemon240;
            case 241:
                return R.mipmap.pokemon241;
            case 242:
                return R.mipmap.pokemon242;
            case 243:
                return R.mipmap.pokemon243;
            case 244:
                return R.mipmap.pokemon244;
            case 245:
                return R.mipmap.pokemon245;
            case 246:
                return R.mipmap.pokemon246;
            case 247:
                return R.mipmap.pokemon247;
            case 248:
                return R.mipmap.pokemon248;
            case 249:
                return R.mipmap.pokemon249;
            case 250:
                return R.mipmap.pokemon250;
            case 251:
                return R.mipmap.pokemon251;
            case 252:
                return R.mipmap.pokemon252;
            case 253:
                return R.mipmap.pokemon253;
            case 254:
                return R.mipmap.pokemon254;
            case 255:
                return R.mipmap.pokemon255;
            case 256:
                return R.mipmap.pokemon256;
            case 257:
                return R.mipmap.pokemon257;
            case 258:
                return R.mipmap.pokemon258;
            case 259:
                return R.mipmap.pokemon259;
            case 260:
                return R.mipmap.pokemon260;
            case 261:
                return R.mipmap.pokemon261;
            case 262:
                return R.mipmap.pokemon262;
            case 263:
                return R.mipmap.pokemon263;
            case 264:
                return R.mipmap.pokemon264;
            case 265:
                return R.mipmap.pokemon265;
            case 266:
                return R.mipmap.pokemon266;
            case 267:
                return R.mipmap.pokemon267;
            case 268:
                return R.mipmap.pokemon268;
            case 269:
                return R.mipmap.pokemon269;
            case 270:
                return R.mipmap.pokemon270;
            case 271:
                return R.mipmap.pokemon271;
            case 272:
                return R.mipmap.pokemon272;
            case 273:
                return R.mipmap.pokemon273;
            case 274:
                return R.mipmap.pokemon274;
            case 275:
                return R.mipmap.pokemon275;
            case 276:
                return R.mipmap.pokemon276;
            case 277:
                return R.mipmap.pokemon277;
            case 278:
                return R.mipmap.pokemon278;
            case 279:
                return R.mipmap.pokemon279;
            case 280:
                return R.mipmap.pokemon280;
            case 281:
                return R.mipmap.pokemon281;
            case 282:
                return R.mipmap.pokemon282;
            case 283:
                return R.mipmap.pokemon283;
            case 284:
                return R.mipmap.pokemon284;
            case 285:
                return R.mipmap.pokemon285;
            case 286:
                return R.mipmap.pokemon286;
            case 287:
                return R.mipmap.pokemon287;
            case 288:
                return R.mipmap.pokemon288;
            case 289:
                return R.mipmap.pokemon289;
            case 290:
                return R.mipmap.pokemon290;
            case 291:
                return R.mipmap.pokemon291;
            case 292:
                return R.mipmap.pokemon292;
            case 293:
                return R.mipmap.pokemon293;
            case 294:
                return R.mipmap.pokemon294;
            case 295:
                return R.mipmap.pokemon295;
            case 296:
                return R.mipmap.pokemon296;
            case 297:
                return R.mipmap.pokemon297;
            case 298:
                return R.mipmap.pokemon298;
            case 299:
                return R.mipmap.pokemon299;
            case 300:
                return R.mipmap.pokemon300;
            case 301:
                return R.mipmap.pokemon301;
            case 302:
                return R.mipmap.pokemon302;
            case 303:
                return R.mipmap.pokemon303;
            case 304:
                return R.mipmap.pokemon304;
            case 305:
                return R.mipmap.pokemon305;
            case 306:
                return R.mipmap.pokemon306;
            case 307:
                return R.mipmap.pokemon307;
            case 308:
                return R.mipmap.pokemon308;
            case 309:
                return R.mipmap.pokemon309;
            case 310:
                return R.mipmap.pokemon310;
            case 311:
                return R.mipmap.pokemon311;
            case 312:
                return R.mipmap.pokemon312;
            case 313:
                return R.mipmap.pokemon313;
            case 314:
                return R.mipmap.pokemon314;
            case 315:
                return R.mipmap.pokemon315;
            case 316:
                return R.mipmap.pokemon316;
            case 317:
                return R.mipmap.pokemon317;
            case 318:
                return R.mipmap.pokemon318;
            case 319:
                return R.mipmap.pokemon319;
            case 320:
                return R.mipmap.pokemon320;
            case 321:
                return R.mipmap.pokemon321;
            case 322:
                return R.mipmap.pokemon322;
            case 323:
                return R.mipmap.pokemon323;
            case 324:
                return R.mipmap.pokemon324;
            case 325:
                return R.mipmap.pokemon325;
            case 326:
                return R.mipmap.pokemon326;
            case 327:
                return R.mipmap.pokemon327;
            case 328:
                return R.mipmap.pokemon328;
            case 329:
                return R.mipmap.pokemon329;
            case 330:
                return R.mipmap.pokemon330;
            case 331:
                return R.mipmap.pokemon331;
            case 332:
                return R.mipmap.pokemon332;
            case 333:
                return R.mipmap.pokemon333;
            case 334:
                return R.mipmap.pokemon334;
            case 335:
                return R.mipmap.pokemon335;
            case 336:
                return R.mipmap.pokemon336;
            case 337:
                return R.mipmap.pokemon337;
            case 338:
                return R.mipmap.pokemon338;
            case 339:
                return R.mipmap.pokemon339;
            case 340:
                return R.mipmap.pokemon340;
            case 341:
                return R.mipmap.pokemon341;
            case 342:
                return R.mipmap.pokemon342;
            case 343:
                return R.mipmap.pokemon343;
            case 344:
                return R.mipmap.pokemon344;
            case 345:
                return R.mipmap.pokemon345;
            case 346:
                return R.mipmap.pokemon346;
            case 347:
                return R.mipmap.pokemon347;
            case 348:
                return R.mipmap.pokemon348;
            case 349:
                return R.mipmap.pokemon349;
            case 350:
                return R.mipmap.pokemon350;
            case 351:
                return R.mipmap.pokemon351;
            case 352:
                return R.mipmap.pokemon352;
            case 353:
                return R.mipmap.pokemon353;
            case 354:
                return R.mipmap.pokemon354;
            case 355:
                return R.mipmap.pokemon355;
            case 356:
                return R.mipmap.pokemon356;
            case 357:
                return R.mipmap.pokemon357;
            case 358:
                return R.mipmap.pokemon358;
            case 359:
                return R.mipmap.pokemon359;
            case 360:
                return R.mipmap.pokemon360;
            case 361:
                return R.mipmap.pokemon361;
            case 362:
                return R.mipmap.pokemon362;
            case 363:
                return R.mipmap.pokemon363;
            case 364:
                return R.mipmap.pokemon364;
            case 365:
                return R.mipmap.pokemon365;
            case 366:
                return R.mipmap.pokemon366;
            case 367:
                return R.mipmap.pokemon367;
            case 368:
                return R.mipmap.pokemon368;
            case 369:
                return R.mipmap.pokemon369;
            case 370:
                return R.mipmap.pokemon370;
            case 371:
                return R.mipmap.pokemon371;
            case 372:
                return R.mipmap.pokemon372;
            case 373:
                return R.mipmap.pokemon373;
            case 374:
                return R.mipmap.pokemon374;
            case 375:
                return R.mipmap.pokemon375;
            case 376:
                return R.mipmap.pokemon376;
            case 377:
                return R.mipmap.pokemon377;
            case 378:
                return R.mipmap.pokemon378;
            case 379:
                return R.mipmap.pokemon379;
            case 380:
                return R.mipmap.pokemon380;
            case 381:
                return R.mipmap.pokemon381;
            case 382:
                return R.mipmap.pokemon382;
            case 383:
                return R.mipmap.pokemon383;
            case 384:
                return R.mipmap.pokemon384;
            case 385:
                return R.mipmap.pokemon385;
            case 386:
                return R.mipmap.pokemon386;
            case 387:
                return R.mipmap.pokemon387;
            case 388:
                return R.mipmap.pokemon388;
            case 389:
                return R.mipmap.pokemon389;
            case 390:
                return R.mipmap.pokemon390;
            case 391:
                return R.mipmap.pokemon391;
            case 392:
                return R.mipmap.pokemon392;
            case 393:
                return R.mipmap.pokemon393;
            case 394:
                return R.mipmap.pokemon394;
            case 395:
                return R.mipmap.pokemon395;
            case 396:
                return R.mipmap.pokemon396;
            case 397:
                return R.mipmap.pokemon397;
            case 398:
                return R.mipmap.pokemon398;
            case 399:
                return R.mipmap.pokemon399;
            case 400:
                return R.mipmap.pokemon400;
            case 401:
                return R.mipmap.pokemon401;
            case 402:
                return R.mipmap.pokemon402;
            case 403:
                return R.mipmap.pokemon403;
            case 404:
                return R.mipmap.pokemon404;
            case 405:
                return R.mipmap.pokemon405;
            case 406:
                return R.mipmap.pokemon406;
            case 407:
                return R.mipmap.pokemon407;
            case 408:
                return R.mipmap.pokemon408;
            case 409:
                return R.mipmap.pokemon409;
            case 410:
                return R.mipmap.pokemon410;
            case 411:
                return R.mipmap.pokemon411;
            case 412:
                return R.mipmap.pokemon412;
            case 413:
                return R.mipmap.pokemon413;
            case 414:
                return R.mipmap.pokemon414;
            case 415:
                return R.mipmap.pokemon415;
            case 416:
                return R.mipmap.pokemon416;
            case 417:
                return R.mipmap.pokemon417;
            case 418:
                return R.mipmap.pokemon418;
            case 419:
                return R.mipmap.pokemon419;
            case 420:
                return R.mipmap.pokemon420;
            case 421:
                return R.mipmap.pokemon421;
            case 422:
                return R.mipmap.pokemon422;
            case 423:
                return R.mipmap.pokemon423;
            case 424:
                return R.mipmap.pokemon424;
            case 425:
                return R.mipmap.pokemon425;
            case 426:
                return R.mipmap.pokemon426;
            case 427:
                return R.mipmap.pokemon427;
            case 428:
                return R.mipmap.pokemon428;
            case 429:
                return R.mipmap.pokemon429;
            case 430:
                return R.mipmap.pokemon430;
            case 431:
                return R.mipmap.pokemon431;
            case 432:
                return R.mipmap.pokemon432;
            case 433:
                return R.mipmap.pokemon433;
            case 434:
                return R.mipmap.pokemon434;
            case 435:
                return R.mipmap.pokemon435;
            case 436:
                return R.mipmap.pokemon436;
            case 437:
                return R.mipmap.pokemon437;
            case 438:
                return R.mipmap.pokemon438;
            case 439:
                return R.mipmap.pokemon439;
            case 440:
                return R.mipmap.pokemon440;
            case 441:
                return R.mipmap.pokemon441;
            case 442:
                return R.mipmap.pokemon442;
            case 443:
                return R.mipmap.pokemon443;
            case 444:
                return R.mipmap.pokemon444;
            case 445:
                return R.mipmap.pokemon445;
            case 446:
                return R.mipmap.pokemon446;
            case 447:
                return R.mipmap.pokemon447;
            case 448:
                return R.mipmap.pokemon448;
            case 449:
                return R.mipmap.pokemon449;
            case 450:
                return R.mipmap.pokemon450;
            case 451:
                return R.mipmap.pokemon451;
            case 452:
                return R.mipmap.pokemon452;
            case 453:
                return R.mipmap.pokemon453;
            case 454:
                return R.mipmap.pokemon454;
            case 455:
                return R.mipmap.pokemon455;
            case 456:
                return R.mipmap.pokemon456;
            case 457:
                return R.mipmap.pokemon457;
            case 458:
                return R.mipmap.pokemon458;
            case 459:
                return R.mipmap.pokemon459;
            case 460:
                return R.mipmap.pokemon460;
            case 461:
                return R.mipmap.pokemon461;
            case 462:
                return R.mipmap.pokemon462;
            case 463:
                return R.mipmap.pokemon463;
            case 464:
                return R.mipmap.pokemon464;
            case 465:
                return R.mipmap.pokemon465;
            case 466:
                return R.mipmap.pokemon466;
            case 467:
                return R.mipmap.pokemon467;
            case 468:
                return R.mipmap.pokemon468;
            case 469:
                return R.mipmap.pokemon469;
            case 470:
                return R.mipmap.pokemon470;
            case 471:
                return R.mipmap.pokemon471;
            case 472:
                return R.mipmap.pokemon472;
            case 473:
                return R.mipmap.pokemon473;
            case 474:
                return R.mipmap.pokemon474;
            case 475:
                return R.mipmap.pokemon475;
            case 476:
                return R.mipmap.pokemon476;
            case 477:
                return R.mipmap.pokemon477;
            case 478:
                return R.mipmap.pokemon478;
            case 479:
                return R.mipmap.pokemon479;
            case 480:
                return R.mipmap.pokemon480;
            case 481:
                return R.mipmap.pokemon481;
            case 482:
                return R.mipmap.pokemon482;
            case 483:
                return R.mipmap.pokemon483;
            case 484:
                return R.mipmap.pokemon484;
            case 485:
                return R.mipmap.pokemon485;
            case 486:
                return R.mipmap.pokemon486;
            case 487:
                return R.mipmap.pokemon487;
            case 488:
                return R.mipmap.pokemon488;
            case 489:
                return R.mipmap.pokemon489;
            case 490:
                return R.mipmap.pokemon490;
            case 491:
                return R.mipmap.pokemon491;
            case 492:
                return R.mipmap.pokemon492;
            case 493:
                return R.mipmap.pokemon493;
            default:
                return R.mipmap.pokemon493;
        }
    }

    /**
     * Devuelve el id de la imagen del tipo
     *
     * @param tipo Tipo a buscar id
     * @return id del recurso
     */
    public static int getIdRecursoTipo(int tipo) {
        switch (tipo) {
            case 1:
                return R.mipmap.acero;
            case 2:
                return R.mipmap.agua;
            case 3:
                return R.mipmap.bicho;
            case 4:
                return R.mipmap.dragon;
            case 5:
                return R.mipmap.electrico;
            case 6:
                return R.mipmap.fantasma;
            case 7:
                return R.mipmap.fuego;
            case 9:
                return R.mipmap.hielo;
            case 10:
                return R.mipmap.lucha;
            case 11:
                return R.mipmap.normal;
            case 12:
                return R.mipmap.planta;
            case 13:
                return R.mipmap.psiquico;
            case 14:
                return R.mipmap.roca;
            case 15:
                return R.mipmap.siniestro;
            case 16:
                return R.mipmap.tierra;
            case 17:
                return R.mipmap.veneno;
            case 18:
                return R.mipmap.volador;
            default:
                return Integer.MAX_VALUE;
        }
    }

}
